name: Release
on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Build the project
      run: npm run build  # Adjust this to your build command
    - run: npx semantic-release
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}